[pytest]
DJANGO_SETTINGS_MODULE = ZooMatch.settings
python_files = tests.py test_*.py *_tests.py
testpaths = 
    api_tests
    ui_tests/tests

addopts = -q --tb=no
norecursedirs = 
    venv 
    .venv 
    __pycache__ 
    *.egg-info

log_cli = true
log_cli_level = INFO
log_file = test.log
log_file_level = INFO