# Generated by Django 5.2 on 2025-11-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
