# Generated by Django 5.2 on 2026-05-27 19:38

import core.uploads
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=core.uploads.user_avatar_path, validators=[core.validators.validate_file_size, core.validators.validate_image_type]),
        ),
    ]
