# Generated by Django 5.2 on 2026-04-22 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0010_rename_content_comment_text_comment_media_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='pets.pet')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.actioncategory')),
            ],
        ),
        migrations.CreateModel(
            name='Rejection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1)),
                ('last_rejected_at', models.DateTimeField(auto_now=True)),
                ('pet_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejections_sent', to='pets.pet')),
                ('pet_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejections_received', to='pets.pet')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Rejected'), (3, 'Closed')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_matches', to='pets.pet')),
                ('pet_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_matches', to='pets.pet')),
            ],
            options={
                'unique_together': {('pet_from', 'pet_to')},
            },
        ),
    ]
