# Generated by Django 5.2 on 2026-05-03 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
        ('pets', '0010_rename_content_comment_text_comment_media_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rejection',
            unique_together={('pet_from', 'pet_to')},
        ),
    ]
