# Generated by Django 5.2 on 2026-05-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_alter_rejection_unique_together'),
        ('pets', '0011_alter_comment_pet_info_card_alter_pet_is_active_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='match',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='rejection',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['status'], name='matching_ma_status_8042fa_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['created_at'], name='matching_ma_created_9824e1_idx'),
        ),
        migrations.AddIndex(
            model_name='rejection',
            index=models.Index(fields=['count'], name='matching_re_count_8f9510_idx'),
        ),
        migrations.AddIndex(
            model_name='rejection',
            index=models.Index(fields=['last_rejected_at'], name='matching_re_last_re_44e938_idx'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('pet_from', 'pet_to'), name='unique_match'),
        ),
    ]
