# Generated by Django 5.2 on 2026-05-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_alter_match_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='value',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
