# Generated by Django 5.2 on 2026-05-15 14:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_alter_message_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='chats_messa_sender__25fc38_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='chats_messa_receive_243349_idx',
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'receiver', '-created_at'], name='chats_messa_sender__ba63ee_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['receiver', 'sender', '-created_at'], name='chats_messa_receive_d56f87_idx'),
        ),
    ]
