# Generated by Django 5.2 on 2026-05-27 19:38

import core.uploads
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=core.uploads.message_media_path, validators=[core.validators.validate_media_type, core.validators.validate_file_size]),
        ),
    ]
