# Generated by Django 5.2 on 2025-11-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='tag',
            field=models.ManyToManyField(to='pets.tag'),
        ),
    ]
