# Generated by Django 5.2 on 2025-11-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_pet_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='tag',
        ),
        migrations.AddField(
            model_name='pet',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='pets', to='pets.tag'),
        ),
    ]
