# Generated by Django 5.2 on 2025-11-10 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_remove_pet_tag_pet_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
    ]
