# Generated by Django 5.2 on 2025-11-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_rename_user_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='avatar',
            field=models.FilePathField(blank=True, null=True, path='media/pet-files/avatars'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pedigree_documents',
            field=models.FilePathField(blank=True, null=True, path='media/pet-files/pedigree-documents'),
        ),
    ]
