# Generated by Django 5.2 on 2025-11-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_alter_pet_avatar_alter_pet_pedigree_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='avatar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
