# Generated by Django 5.2 on 2025-11-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_alter_pet_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pedigree_documents',
            field=models.TextField(blank=True, null=True),
        ),
    ]
