# Generated by Django 5.2 on 2025-11-16 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0008_alter_pet_pedigree_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_from', to='pets.pet')),
                ('pet_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_to', to='pets.pet')),
            ],
            options={
                'unique_together': {('pet_from', 'pet_to')},
            },
        ),
    ]
