# Generated by Django 5.2 on 2026-04-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0009_match'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='text',
        ),
        migrations.AddField(
            model_name='comment',
            name='media',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Match',
        ),
    ]
