# Generated by Django 5.2 on 2026-05-15 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0010_rename_content_comment_text_comment_media_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pet_info_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='pets.petinfo'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['animal_type', 'breed'], name='pets_pet_animal__d8c013_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['animal_type', 'is_active'], name='pets_pet_animal__c20d5f_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['location', 'animal_type'], name='pets_pet_locatio_4554f5_idx'),
        ),
    ]
