# Generated by Django 5.2 on 2026-05-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0011_alter_comment_pet_info_card_alter_pet_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
