# Generated by Django 5.2 on 2026-05-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0012_alter_pet_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='location',
            field=models.CharField(default=(54.199996, 37.580795), max_length=100),
            preserve_default=False,
        ),
    ]
