# Generated by Django 5.2 on 2026-05-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0012_alter_pet_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='last_mating_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='mating_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
