# Generated by Django 5.2 on 2026-05-27 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0013_alter_pet_location'),
        ('pets', '0013_pet_last_mating_date_pet_mating_count'),
    ]

    operations = [
    ]
