# Generated by Django 5.2 on 2026-05-27 19:38

import core.uploads
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0014_merge_20260527_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=core.uploads.comment_media_path, validators=[core.validators.validate_file_size, core.validators.validate_media_type]),
        ),
        migrations.AlterField(
            model_name='pet',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=core.uploads.pet_avatar_path, validators=[core.validators.validate_file_size, core.validators.validate_image_type]),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pedigree_documents',
            field=models.FileField(blank=True, null=True, upload_to=core.uploads.pet_document_path, validators=[core.validators.validate_file_size, core.validators.validate_pdf_type]),
        ),
    ]
