# Generated by Django 5.2 on 2026-06-21 14:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0015_alter_comment_media_alter_pet_avatar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], db_index=True, default='approved', max_length=20),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['is_active', 'moderation_status'], name='pets_pet_is_acti_47ffa8_idx'),
        ),
    ]
