# Generated by Django 5.2 on 2026-05-25 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0013_pet_last_mating_date_pet_mating_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_ids', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_cache', to='pets.pet')),
            ],
            options={
                'indexes': [models.Index(fields=['updated_at'], name='recommendat_updated_f6151e_idx')],
            },
        ),
    ]
