# Generated by Django 5.2 on 2026-05-25 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0013_pet_last_mating_date_pet_mating_count'),
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendationcache',
            name='pet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_cache', to='pets.pet'),
        ),
        migrations.CreateModel(
            name='RecommendationParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radius_km', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('requires_pedigree', models.BooleanField(default=False)),
                ('min_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_months_since_mating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_params', to='pets.pet')),
            ],
        ),
    ]
